import React from 'react';

const AboutUs = () => {
    return(
        <div className='about-us-main'>
            <h1 className='about-us-heading'>About Us</h1>
            <p> <strong>Business World Trade</strong> Lorem ipsum dcing elit. Consectetur vel at quo soluta voluptas minima, molestias nemo amet commodi ex voluptatibus? Nulla, voluptatem consequatur incidunt aspernatur officiis quibusdam ea maiores. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit cupiditate quasi voluptate nesciunt et deserunt nemo, unde labore eligendi aspernatur? Dolore, error reiciendis. Nesciunt consectetur, saepe error assumenda adipisci itaque!lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, eveniet consectetur debitis id ducimus suscipit aut? Quasi mollitia nostrum facilis soluta blanditiis? Incidunt laborum exercitationem libero consequatur accusamus iste autem?</p>
            <p>Lorem ipsum dcing elit. Consectetur vel at quo soluta voluptas minima, molestias nemo amet commodi ex voluptatibus? Nulla, voluptatem consequatur incidunt aspernatur officiis quibusdam ea maiores. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit cupiditate quasi voluptate nesciunt et deserunt nemo, unde labore eligendi aspernatur? Dolore, error reiciendis. Nesciunt consectetur, saepe error assumenda adipisci itaque!lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, eveniet consectetur debitis id ducimus suscipit aut? Quasi mollitia nostrum facilis soluta blanditiis? Incidunt laborum exercitationem libero consequatur accusamus iste autem?</p>
            <p><strong>Our Mission</strong> <br /> Lorem ipsum dcing elit. Consectetur vel at quo soluta voluptas minima, molestias nemo amet commodi ex voluptatibus? Nulla, voluptatem consequatur incidunt aspernatur officiis quibusdam ea maiores. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit cupiditate quasi voluptate nesciunt et deserunt nemo, unde labore eligendi aspernatur? Dolore, error reiciendis. Nesciunt consectetur, saepe error assumenda adipisci itaque!lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, eveniet consectetur debitis id ducimus suscipit aut? Quasi mollitia nostrum facilis soluta blanditiis? Incidunt laborum exercitationem libero consequatur accusamus iste autem?</p>
            <p><strong>Our Vision</strong> <br /> Lorem ipsum dcing elit. Consectetur vel at quo soluta voluptas minima, molestias nemo amet commodi ex voluptatibus? Nulla, voluptatem consequatur incidunt aspernatur officiis quibusdam ea maiores. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit cupiditate quasi voluptate nesciunt et deserunt nemo, unde labore eligendi aspernatur? Dolore, error reiciendis. Nesciunt consectetur, saepe error assumenda adipisci itaque!lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, eveniet consectetur debitis id ducimus suscipit aut? Quasi mollitia nostrum facilis soluta blanditiis? Incidunt laborum exercitationem libero consequatur accusamus iste autem?</p>
        </div>
    )
}
export default AboutUs
